<!DOCTYPE html>
<html lang="es" class="scroll-smooth">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="description" content="NOVA Community conecta administradores de fincas, comunidades, empleados de mantenimiento y propietarios en una única plataforma.">
    <title>NOVA Community — Gestión integral para administradores de fincas</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        [x-cloak] { display: none !important; }
        .nova-grid { background-image: linear-gradient(rgba(255,255,255,.025) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.025) 1px, transparent 1px); background-size: 42px 42px; }
        .nova-glass { background: linear-gradient(145deg, rgba(30,34,40,.82), rgba(15,18,23,.72)); border: 1px solid rgba(255,255,255,.11); box-shadow: inset 0 1px 0 rgba(255,255,255,.06), 0 24px 70px rgba(0,0,0,.28); backdrop-filter: blur(22px); }
        .nova-card { transition: transform .3s ease, border-color .3s ease, box-shadow .3s ease; }
        .nova-card:hover { transform: translateY(-4px); border-color: rgba(248,113,113,.34); box-shadow: 0 22px 60px rgba(0,0,0,.34); }
        .phone-shell { width: min(100%, 310px); aspect-ratio: 310 / 620; border: 7px solid #272a30; border-radius: 2.65rem; background: #06090d; box-shadow: 0 36px 90px rgba(0,0,0,.55), inset 0 0 0 1px rgba(255,255,255,.1); overflow: hidden; }
        .admin-shell { border: 1px solid rgba(255,255,255,.14); border-radius: 1.5rem; background: #090c11; box-shadow: 0 40px 100px rgba(0,0,0,.55); overflow: hidden; }
    </style>
</head>
<body class="bg-[#07090d] font-['Montserrat'] text-white antialiased selection:bg-red-600 selection:text-white">
    <header class="sticky top-0 z-50 border-b border-white/10 bg-[#07090d]/80 backdrop-blur-2xl">
        <nav class="mx-auto flex h-16 max-w-7xl items-center justify-between gap-5 px-4 md:px-8" aria-label="Navegación principal">
            <a href="#inicio" class="flex items-center gap-3 font-extrabold tracking-tight">
                <span class="grid h-9 w-9 place-items-center rounded-xl bg-red-600 shadow-lg shadow-red-600/20">
                    <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.3"><path d="M4 21V7l8-4 8 4v14M8 10h2m4 0h2M8 14h2m4 0h2M9 21v-4h6v4"/></svg>
                </span>
                <span>NOVA <span class="text-red-500">Community</span></span>
            </a>
            <div class="hidden items-center gap-6 text-xs font-semibold text-white/60 lg:flex">
                <a href="#ecosistema" class="transition hover:text-white">Ecosistema</a>
                <a href="#administracion" class="transition hover:text-white">Administración</a>
                <a href="#empleados" class="transition hover:text-white">Empleados</a>
                <a href="#propietarios" class="transition hover:text-white">Propietarios</a>
                <a href="#automatizacion" class="transition hover:text-white">Automatización</a>
            </div>
            <a href="{{ url('/comunigest/login') }}" class="rounded-xl bg-red-600 px-4 py-2.5 text-xs font-bold shadow-lg shadow-red-600/20 transition hover:-translate-y-0.5 hover:bg-red-500">Acceder a la app</a>
        </nav>
    </header>

    <main>
        <section id="inicio" class="nova-grid relative overflow-hidden px-4 py-20 md:px-8 md:py-28">
            <div class="pointer-events-none absolute left-1/2 top-0 h-[520px] w-[850px] -translate-x-1/2 rounded-full bg-red-700/15 blur-[130px]"></div>
            <div class="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]">
                <div>
                    <span class="inline-flex items-center gap-2 rounded-full border border-red-400/20 bg-red-500/10 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.18em] text-red-300"><span class="h-2 w-2 rounded-full bg-red-500"></span> El sistema operativo de tu administración de fincas</span>
                    <h1 class="mt-6 text-4xl font-extrabold leading-[1.06] tracking-[-.04em] sm:text-5xl lg:text-7xl">Comunidades, equipo y propietarios.<br><span class="bg-gradient-to-r from-red-400 to-orange-300 bg-clip-text text-transparent">Todo conectado.</span></h1>
                    <p class="mt-6 max-w-2xl text-base leading-8 text-white/60 md:text-lg">NOVA Community permite gestionar múltiples comunidades desde una sola empresa, coordinar el mantenimiento, automatizar planes de trabajo y ofrecer a cada propietario información económica y documental clara.</p>
                    <div class="mt-8 flex flex-wrap gap-3">
                        <a href="#contacto" class="rounded-xl bg-red-600 px-6 py-3.5 text-sm font-bold shadow-xl shadow-red-600/20 transition hover:-translate-y-1 hover:bg-red-500">Solicitar demostración</a>
                        <a href="#experiencias" class="rounded-xl border border-white/15 bg-white/5 px-6 py-3.5 text-sm font-bold backdrop-blur transition hover:-translate-y-1 hover:bg-white/10">Ver las tres apps</a>
                    </div>
                    <div class="mt-10 grid max-w-2xl grid-cols-2 gap-3 sm:grid-cols-4">
                        @foreach ([['Comunidades','48'],['Empleados','18'],['Tareas hoy','126'],['Propietarios','1.240']] as [$label, $value])
                            <div class="rounded-2xl border border-white/10 bg-white/[.035] p-4"><strong class="text-xl">{{ $value }}</strong><p class="mt-1 text-[10px] uppercase tracking-wider text-white/35">{{ $label }}</p></div>
                        @endforeach
                    </div>
                </div>

                <div class="nova-glass relative rounded-[2rem] p-4 sm:p-6">
                    <div class="flex items-center justify-between border-b border-white/10 pb-4"><div><p class="text-[10px] font-bold uppercase tracking-[.2em] text-red-400">Operaciones de hoy</p><h2 class="mt-1 font-bold">Vista global de la empresa</h2></div><span class="rounded-full bg-emerald-500/10 px-3 py-1 text-[10px] font-bold text-emerald-300">OPERATIVO</span></div>
                    <div class="mt-4 grid grid-cols-2 gap-3">
                        @foreach ([['Órdenes activas','19','text-cyan-300'],['Incidencias','6','text-red-300'],['Personal en servicio','12','text-emerald-300'],['Planes completados','84%','text-violet-300']] as [$label,$value,$color])
                            <div class="rounded-2xl border border-white/10 bg-black/20 p-4"><p class="text-[10px] uppercase tracking-wider text-white/35">{{ $label }}</p><p class="mt-2 text-2xl font-light {{ $color }}">{{ $value }}</p></div>
                        @endforeach
                    </div>
                    <div class="mt-3 rounded-2xl border border-white/10 bg-black/20 p-4">
                        <div class="flex items-center justify-between"><p class="text-xs font-bold">Progreso por comunidad</p><span class="text-[10px] text-white/35">En tiempo real</span></div>
                        @foreach ([['Los Marinos',92,'bg-emerald-500'],['Residencial Atlántico',74,'bg-cyan-500'],['Jardines del Sur',58,'bg-amber-500']] as [$name,$progress,$color])
                            <div class="mt-4"><div class="mb-1.5 flex justify-between text-[10px]"><span>{{ $name }}</span><span class="text-white/45">{{ $progress }}%</span></div><div class="h-1.5 overflow-hidden rounded-full bg-white/10"><div class="h-full rounded-full {{ $color }}" style="width: {{ $progress }}%"></div></div></div>
                        @endforeach
                    </div>
                </div>
            </div>
        </section>

        <section id="ecosistema" class="border-y border-white/10 bg-[#0a0d12] px-4 py-20 md:px-8">
            <div class="mx-auto max-w-7xl">
                <div class="mx-auto max-w-3xl text-center"><p class="text-xs font-bold uppercase tracking-[.2em] text-red-400">Un único ecosistema</p><h2 class="mt-3 text-3xl font-extrabold md:text-5xl">Cuatro actores, una misma información</h2><p class="mt-4 leading-7 text-white/50">La empresa administra. Cada comunidad contrata y organiza sus servicios. Los empleados ejecutan. Los propietarios consultan, pagan y se comunican.</p></div>
                <div class="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                    @foreach ([
                        ['EMPRESA','Administrador de fincas','Control transversal de comunidades, departamentos, equipo, economía, documentos y atención.','01','from-red-500/20'],
                        ['CONTEXTO','Comunidades','Propiedades, propietarios, cuotas, planes, órdenes, tareas, incidencias y progreso operativo.','02','from-cyan-500/20'],
                        ['OPERACIÓN','Empleados','Turnos, plan diario optimizado, ejecución, asistencia, geolocalización, fotos, notas y audio.','03','from-emerald-500/20'],
                        ['SERVICIO','Propietarios','Propiedades, cuotas, pagos, documentos, avisos, citas, tickets e incidencias con fotografías.','04','from-violet-500/20'],
                    ] as [$eyebrow,$title,$text,$number,$gradient])
                        <article class="nova-card rounded-3xl border border-white/10 bg-gradient-to-br {{ $gradient }} to-white/[.025] p-6"><span class="text-3xl font-light text-white/20">{{ $number }}</span><p class="mt-8 text-[10px] font-bold tracking-[.18em] text-white/35">{{ $eyebrow }}</p><h3 class="mt-2 text-xl font-bold">{{ $title }}</h3><p class="mt-3 text-sm leading-6 text-white/50">{{ $text }}</p></article>
                    @endforeach
                </div>
            </div>
        </section>

        <section id="experiencias" x-data="{ app: 'admin' }" class="px-4 py-20 md:px-8">
            <div class="mx-auto max-w-7xl">
                <div class="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div class="max-w-3xl"><p class="text-xs font-bold uppercase tracking-[.2em] text-red-400">Tres experiencias conectadas</p><h2 class="mt-3 text-3xl font-extrabold md:text-5xl">Una app para cada forma de trabajar</h2><p class="mt-4 leading-7 text-white/50">Interfaces específicas, simples y conectadas a los mismos datos. Sin duplicar procesos ni mantener aplicaciones aisladas.</p></div><div class="flex rounded-2xl border border-white/10 bg-white/5 p-1">@foreach (['admin' => 'APP ADMIN','employee' => 'APP EMPLEADO','owner' => 'APP PROPIETARIO'] as $key => $label)<button type="button" @click="app='{{ $key }}'" :class="app === '{{ $key }}' ? 'bg-red-600 text-white shadow-lg' : 'text-white/45 hover:text-white'" class="rounded-xl px-3 py-2.5 text-[10px] font-bold transition sm:px-4">{{ $label }}</button>@endforeach</div></div>

                <div class="mt-10">
                    <div x-show="app === 'admin'" x-transition.opacity class="grid items-center gap-10 lg:grid-cols-[.38fr_.62fr]">
                        <div><span class="rounded-full bg-red-500/10 px-3 py-1 text-[10px] font-bold text-red-300">APP ADMIN</span><h3 class="mt-5 text-3xl font-bold">Decide con una visión completa</h3><p class="mt-4 leading-7 text-white/50">El administrador visualiza turnos, planes, órdenes pendientes, incidencias, productividad de empleados y nivel de servicio por comunidad.</p><ul class="mt-6 grid gap-3 text-sm text-white/70">@foreach (['Dashboard operativo y alertas','Calendarios de planes, órdenes y turnos','Seguimiento de empleados y asistencia','Gestión documental, cuotas y pagos','Citas, tickets, avisos e incidencias'] as $item)<li class="flex gap-3"><span class="text-red-400">✓</span>{{ $item }}</li>@endforeach</ul></div>
                        <div class="admin-shell"><div class="flex h-11 items-center gap-2 border-b border-white/10 bg-white/[.035] px-4"><span class="h-2.5 w-2.5 rounded-full bg-red-500"></span><span class="h-2.5 w-2.5 rounded-full bg-amber-500"></span><span class="h-2.5 w-2.5 rounded-full bg-emerald-500"></span><span class="ml-4 text-[9px] text-white/30">NOVA Community · Operaciones</span></div><div class="grid min-h-[380px] grid-cols-[110px_1fr] sm:grid-cols-[160px_1fr]"><aside class="border-r border-white/10 bg-black/20 p-3">@foreach (['Dashboard','Comunidades','Propiedades','Empleados','Planes','Órdenes','Incidencias','Cuotas'] as $item)<div class="mb-1 rounded-lg px-2 py-2 text-[8px] {{ $loop->first ? 'bg-red-600 text-white' : 'text-white/35' }}">{{ $item }}</div>@endforeach</aside><div class="p-4"><p class="text-[9px] text-white/30">HOY · 15 AGOSTO</p><h4 class="mt-1 text-sm font-bold">Operaciones</h4><div class="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">@foreach ([['Servicios','26'],['Pendientes','8'],['En servicio','12'],['Alertas','3']] as [$l,$v])<div class="rounded-xl border border-white/10 bg-white/[.04] p-3"><p class="text-[7px] text-white/30">{{ $l }}</p><p class="mt-1 text-lg">{{ $v }}</p></div>@endforeach</div><div class="mt-3 grid gap-3 sm:grid-cols-2"><div class="rounded-xl border border-white/10 bg-white/[.04] p-3"><p class="text-[8px] font-bold">Plan diario</p>@foreach ([['08:00','Los Marinos','Juan'],['10:30','Costa Azul','Marta'],['12:15','Las Palmeras','Ángel']] as $r)<div class="mt-2 flex items-center gap-2 border-t border-white/5 pt-2 text-[7px]"><b class="text-red-300">{{ $r[0] }}</b><span class="flex-1">{{ $r[1] }}</span><span class="text-white/30">{{ $r[2] }}</span></div>@endforeach</div><div class="rounded-xl border border-white/10 bg-white/[.04] p-3"><p class="text-[8px] font-bold">Cumplimiento</p>@foreach ([['Juan',91],['Marta',78],['Ángel',66]] as [$n,$p])<div class="mt-3"><div class="flex justify-between text-[7px]"><span>{{ $n }}</span><span>{{ $p }}%</span></div><div class="mt-1 h-1 rounded bg-white/10"><div class="h-full rounded bg-red-500" style="width:{{$p}}%"></div></div></div>@endforeach</div></div></div></div></div>
                    </div>

                    <div x-show="app === 'employee'" x-cloak x-transition.opacity class="grid items-center gap-10 lg:grid-cols-[.55fr_.45fr]"><div class="flex justify-center"><div class="phone-shell p-3"><div class="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.06] px-3 py-3"><div><p class="text-[7px] font-bold tracking-widest text-red-400">NOVA COMMUNITY</p><p class="mt-1 text-xs font-bold">Buenos días, Juan</p></div><span class="grid h-8 w-8 place-items-center rounded-full bg-red-600 text-[9px] font-bold">JP</span></div><div class="mt-3 grid grid-cols-2 gap-2">@foreach ([['PLAN HOY','7','text-violet-300'],['ÓRDENES','3','text-cyan-300'],['INCIDENCIAS','1','text-red-300'],['ASISTENCIA','ACTIVA','text-emerald-300']] as [$l,$v,$c])<div class="rounded-2xl border border-white/10 bg-white/[.045] p-3"><p class="text-[7px] font-bold tracking-wider text-white/35">{{ $l }}</p><p class="mt-2 text-lg {{ $c }}">{{ $v }}</p></div>@endforeach</div><div class="mt-3 rounded-2xl border border-white/10 bg-white/[.045] p-3"><div class="flex justify-between"><div><p class="text-[7px] text-white/35">SIGUIENTE SERVICIO</p><p class="mt-1 text-xs font-bold">Los Marinos</p></div><span class="rounded-full bg-amber-500/10 px-2 py-1 text-[7px] text-amber-300">URGENTE</span></div><p class="mt-3 text-[9px] text-white/50">Revisar sala de bombas · 10:30</p><div class="mt-3 h-1.5 rounded-full bg-white/10"><div class="h-full w-2/3 rounded-full bg-red-500"></div></div><p class="mt-2 text-[7px] text-white/30">4 de 6 tareas realizadas</p></div><div class="mt-3 grid gap-2">@foreach ([['✓','Comprobar presión','Finalizada'],['✓','Fotografiar contador','Finalizada'],['○','Revisar fuga','Pendiente']] as [$i,$t,$s])<div class="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.035] p-2.5"><span class="grid h-6 w-6 place-items-center rounded-lg bg-red-500/10 text-[9px] text-red-300">{{ $i }}</span><span class="flex-1 text-[8px]">{{ $t }}</span><span class="text-[6px] text-white/25">{{ $s }}</span></div>@endforeach</div><button class="mt-3 w-full rounded-xl bg-red-600 py-3 text-[9px] font-bold">FINALIZAR SERVICIO</button></div></div><div><span class="rounded-full bg-emerald-500/10 px-3 py-1 text-[10px] font-bold text-emerald-300">APP EMPLEADO</span><h3 class="mt-5 text-3xl font-bold">Cada jornada, ordenada y documentada</h3><p class="mt-4 leading-7 text-white/50">El empleado recibe un plan diario priorizado por urgencia y desplazamientos. Marca tareas, adjunta fotos y cierra el servicio con ubicación, horario y resumen de voz transcrito.</p><ul class="mt-6 grid gap-3 text-sm text-white/70">@foreach (['Ruta diaria optimizada por IA','Tareas, órdenes e incidencias','Check-in/out con geolocalización','Fotos y notas por tarea','Audio final conservado y transcrito'] as $item)<li class="flex gap-3"><span class="text-emerald-400">✓</span>{{ $item }}</li>@endforeach</ul></div></div>

                    <div x-show="app === 'owner'" x-cloak x-transition.opacity class="grid items-center gap-10 lg:grid-cols-[.38fr_.62fr]"><div><span class="rounded-full bg-violet-500/10 px-3 py-1 text-[10px] font-bold text-violet-300">APP PROPIETARIO</span><h3 class="mt-5 text-3xl font-bold">Transparencia y atención sin fricción</h3><p class="mt-4 leading-7 text-white/50">Cada propietario consulta sus propiedades, cuotas, recibos y documentos; paga online y contacta con la administración desde una experiencia sencilla.</p><ul class="mt-6 grid gap-3 text-sm text-white/70">@foreach (['Propiedades y situación de cuotas','Pago mediante pasarela segura','Documentación clasificada','Cita previa con disponibilidad real','Tickets e incidencias con fotografías'] as $item)<li class="flex gap-3"><span class="text-violet-400">✓</span>{{ $item }}</li>@endforeach</ul></div><div class="flex justify-center"><div class="phone-shell p-3"><div class="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.06] px-3 py-3"><div><p class="text-[7px] font-bold tracking-widest text-red-400">NOVA COMMUNITY</p><p class="mt-1 text-xs font-bold">Laura Martínez</p></div><span class="grid h-8 w-8 place-items-center rounded-full bg-violet-600 text-[9px] font-bold">LM</span></div><div class="mt-3 rounded-2xl border border-white/10 bg-gradient-to-br from-violet-500/15 to-white/[.03] p-4"><p class="text-[7px] text-white/35">MI PROPIEDAD</p><p class="mt-1 text-sm font-bold">Los Marinos · 2º B</p><p class="mt-1 text-[8px] text-white/35">Av. del Atlántico, 24</p><div class="mt-4 flex items-end justify-between"><div><p class="text-[7px] text-white/35">CUOTAS PENDIENTES</p><p class="mt-1 text-2xl">126,40 €</p></div><button class="rounded-lg bg-red-600 px-3 py-2 text-[7px] font-bold">PAGAR</button></div></div><div class="mt-3 grid grid-cols-2 gap-2">@foreach ([['DOCUMENTOS','12','text-amber-300'],['CUOTAS','6','text-emerald-300'],['CITAS','1','text-blue-300'],['TICKETS','2','text-red-300']] as [$l,$v,$c])<div class="rounded-2xl border border-white/10 bg-white/[.045] p-3"><p class="text-[7px] font-bold tracking-wider text-white/35">{{ $l }}</p><p class="mt-2 text-lg {{ $c }}">{{ $v }}</p></div>@endforeach</div><div class="mt-3 rounded-2xl border border-white/10 bg-white/[.045] p-3"><p class="text-[8px] font-bold">Últimos movimientos</p>@foreach ([['Recibo agosto','Pagado','text-emerald-300'],['Acta junta ordinaria','PDF','text-amber-300'],['Cita administración','19 Ago · 10:30','text-blue-300']] as [$t,$s,$c])<div class="mt-2 flex justify-between border-t border-white/5 pt-2 text-[7px]"><span>{{ $t }}</span><span class="{{ $c }}">{{ $s }}</span></div>@endforeach</div></div></div></div>
                </div>
                <p class="mt-6 text-center text-[10px] text-white/25">Pantallas simuladas para representar la experiencia de producto.</p>
            </div>
        </section>

        <section id="administracion" x-data="{ slide: 0 }" class="border-y border-white/10 bg-[#0a0d12] px-4 py-20 md:px-8">
            <div class="mx-auto max-w-7xl"><div class="grid gap-10 lg:grid-cols-[.35fr_.65fr]"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-red-400">Gestión del administrador</p><h2 class="mt-3 text-3xl font-extrabold md:text-4xl">De la visión global al detalle de cada tarea</h2><p class="mt-4 leading-7 text-white/50">Selecciona una sección para conocer cómo NOVA Community organiza la operación.</p><div class="mt-6 flex flex-wrap gap-2">@foreach (['Empresa','Comunidades','Equipo','Economía','Atención'] as $index => $label)<button type="button" @click="slide={{ $index }}" :class="slide === {{ $index }} ? 'border-red-400/40 bg-red-500/15 text-red-200' : 'border-white/10 bg-white/[.035] text-white/40 hover:text-white'" class="rounded-xl border px-3 py-2 text-[10px] font-bold transition">{{ $label }}</button>@endforeach</div></div><div class="nova-glass min-h-[330px] rounded-3xl p-6 sm:p-8">@foreach ([
                    ['Una empresa, múltiples comunidades',['Departamentos y permisos','Panel global de alertas','Usuarios, empleados y proveedores','Avisos y comunicaciones']],
                    ['La comunidad como centro operativo',['Propiedades y propietarios','Planes, órdenes y tareas','Incidencias y mantenimiento','Progreso y calendario']],
                    ['Personas, turnos y productividad',['Calendarios de asignación','Presencia y ausencias','Cambios de turno','Cumplimiento por empleado']],
                    ['Cuotas, documentos y pagos',['Cuotas pendientes','Pasarela de pago','Envío documental masivo','Clasificación automática por propiedad']],
                    ['Una relación directa y trazable',['Agenda de cita previa','Tickets y conversaciones','Incidencias con fotos','Avisos y notificaciones']],
                ] as $index => [$title,$items])<div x-show="slide === {{ $index }}" x-cloak x-transition.opacity><p class="text-[10px] font-bold tracking-[.2em] text-red-400">0{{ $index + 1 }}</p><h3 class="mt-3 text-2xl font-bold">{{ $title }}</h3><div class="mt-6 grid gap-3 sm:grid-cols-2">@foreach ($items as $item)<div class="nova-card flex items-center gap-3 rounded-2xl border border-white/10 bg-black/20 p-4"><span class="grid h-8 w-8 place-items-center rounded-lg bg-red-500/10 text-red-300">✓</span><span class="text-sm text-white/70">{{ $item }}</span></div>@endforeach</div></div>@endforeach</div></div></div>
        </section>

        <section id="automatizacion" class="px-4 py-20 md:px-8"><div class="mx-auto max-w-7xl"><div class="mx-auto max-w-3xl text-center"><p class="text-xs font-bold uppercase tracking-[.2em] text-red-400">Automatización útil</p><h2 class="mt-3 text-3xl font-extrabold md:text-5xl">Menos coordinación manual. Más servicio.</h2></div><div class="mt-12 grid gap-5 lg:grid-cols-3">@foreach ([
            ['01','Planes inteligentes','La IA propone planes de tareas recurrentes para múltiples comunidades según tipos de trabajo, urgencia, disponibilidad y desplazamientos.'],
            ['02','Ejecución demostrable','Cada servicio reúne orden, tareas completadas, horas, ubicación, fotografías, notas y grabación final transcrita.'],
            ['03','Documentos sin clasificar a mano','Sube carpetas, ZIP o PDF multipágina y el sistema organiza automáticamente los documentos por propiedad y propietario.'],
        ] as [$number,$title,$text])<article class="nova-card rounded-3xl border border-white/10 bg-white/[.035] p-7"><span class="text-4xl font-light text-red-500/45">{{ $number }}</span><h3 class="mt-8 text-xl font-bold">{{ $title }}</h3><p class="mt-3 text-sm leading-7 text-white/50">{{ $text }}</p></article>@endforeach</div></div></section>

        <section id="empleados" class="border-y border-white/10 bg-[#0a0d12] px-4 py-20 md:px-8"><div class="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-emerald-400">Operación y mantenimiento</p><h2 class="mt-3 text-3xl font-extrabold md:text-5xl">El trabajo realizado deja de estar disperso</h2><p class="mt-5 leading-8 text-white/50">Planes complejos se convierten en órdenes concretas y tareas recurrentes. El empleado sabe qué hacer, dónde y en qué orden; el administrador conoce el progreso sin perseguir actualizaciones.</p></div><div class="grid grid-cols-2 gap-3">@foreach ([['Planes y órdenes','Programación recurrente'],['Turnos','Asignación visual'],['Asistencia','Inicio, fin y ubicación'],['Evidencias','Fotos, texto y audio'],['Incidencias','Prioridad y seguimiento'],['Métricas','Progreso por empleado']] as [$title,$subtitle])<div class="nova-card rounded-2xl border border-white/10 bg-white/[.035] p-4"><p class="text-sm font-bold">{{ $title }}</p><p class="mt-1 text-[10px] text-white/35">{{ $subtitle }}</p></div>@endforeach</div></div></section>

        <section id="propietarios" class="px-4 py-20 md:px-8"><div class="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.45fr_.55fr]"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-violet-400">Administración y propietarios</p><h2 class="mt-3 text-3xl font-extrabold md:text-5xl">Información accesible, pagos más simples</h2><p class="mt-5 leading-8 text-white/50">NOVA Community reduce consultas repetitivas y mejora la transparencia. Cada propietario dispone de un portal con el contexto exacto de sus propiedades.</p></div><div class="grid gap-3 sm:grid-cols-2">@foreach (['Propiedades y datos de la comunidad','Cuotas pagadas y pendientes','Pago online','Documentos, actas y recibos','Cita previa según disponibilidad','Tickets e incidencias con fotos','Avisos y comunicaciones','Historial completo de actividad'] as $item)<div class="nova-card flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.035] p-4"><span class="text-violet-400">✓</span><span class="text-sm text-white/65">{{ $item }}</span></div>@endforeach</div></div></section>

        <section id="contacto" class="px-4 pb-20 md:px-8"><div class="nova-glass relative mx-auto max-w-7xl overflow-hidden rounded-[2rem] px-6 py-12 text-center md:px-12 md:py-16"><div class="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_120%,rgba(220,38,38,.3),transparent_55%)]"></div><div class="relative"><p class="text-xs font-bold uppercase tracking-[.2em] text-red-400">NOVA Community</p><h2 class="mx-auto mt-4 max-w-3xl text-3xl font-extrabold md:text-5xl">Gestiona más comunidades sin perder el control del servicio</h2><p class="mx-auto mt-5 max-w-2xl leading-7 text-white/50">Descubre cómo adaptar la plataforma a la estructura, el equipo y la cartera de tu administración de fincas.</p><div class="mt-8 flex flex-wrap justify-center gap-3"><a href="mailto:info@novacommunity.es?subject=Demostración%20NOVA%20Community" class="rounded-xl bg-red-600 px-6 py-3.5 text-sm font-bold shadow-xl shadow-red-600/20 transition hover:-translate-y-1 hover:bg-red-500">Solicitar demostración</a><a href="{{ url('/comunigest/login') }}" class="rounded-xl border border-white/15 bg-white/5 px-6 py-3.5 text-sm font-bold transition hover:bg-white/10">Acceder a la plataforma</a></div></div></div></section>
    </main>

    <footer class="border-t border-white/10 bg-black/20 px-4 py-8"><div class="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 text-center text-xs text-white/30 sm:flex-row sm:text-left"><p>© 2026 NOVA Community. Gestión inteligente de comunidades.</p><div class="flex gap-5"><a href="#ecosistema" class="hover:text-white">Producto</a><a href="#contacto" class="hover:text-white">Contacto</a><a href="{{ url('/comunigest/login') }}" class="hover:text-white">Acceso</a></div></div></footer>
</body>
</html>
