<?php

namespace App\Filament\App\Resources\BookingDepartments\Pages;

use App\Filament\App\Resources\BookingDepartments\BookingDepartmentResource;
use App\Filament\App\Resources\BookingDepartments\Pages\ManageDepartmentCitas;
use App\Filament\App\Resources\BookingDepartments\Pages\ManageDepartmentTickets;
use App\Filament\App\Resources\BookingDepartments\Pages\ManageDepartmentDocuments;
use App\Filament\App\Resources\BookingDepartments\Pages\ManageTaxistas;
use App\Filament\App\Pages\DepartmentChats;
use App\Models\BookingDepartment;
use App\Models\TaxistaAppointment;
use App\Models\TaxistaTicket;
use App\Models\TaxistaDocument;
use App\Models\Taxista;
use Filament\Actions\Action;
use Filament\Actions\EditAction;
use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\RepeatableEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Actions\Action as InfolistAction;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Actions\Action as SchemaAction;
use Filament\Schemas\Schema;
use Filament\Resources\Pages\ViewRecord;
use Filament\Support\Icons\Heroicon;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\Facades\Route;

class ViewBookingDepartment extends ViewRecord
{
    protected static string $resource = BookingDepartmentResource::class;

    protected static ?string $title = 'Detalle de departamento';
    protected static ?string $navigationLabel = 'Info';

    public function getTitle(): string|Htmlable
    {
        $nombre = BookingDepartment::find($this->record->id)->name;
        return $nombre; // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Action::make('chat')
                ->label('Chat')
                ->icon(Heroicon::OutlinedChatBubbleLeftRight)
                ->url(fn (): string => DepartmentChats::getUrl(['departmentId' => $this->record->id]))
                ->visible(fn (): bool => (bool) $this->record->has_chats_service),
            EditAction::make(),
        ];
    }

    public function infolist(Schema $schema): Schema
    {
        return $schema
            ->schema([
                Section::make('Estadísticas del Departamento')
                    ->description('Resumen de actividades y recursos del departamento')
                    ->columnSpanFull()
                    ->schema([
                        Grid::make(5)
                            ->schema([
                                // Citas Pendientes
                                TextEntry::make('citas_pendientes')
                                    ->label('Citas Pendientes')
                                    ->state(function () {
                                        return TaxistaAppointment::where('booking_department_id', $this->record->id)
                                            ->where('status', 'pendiente')
                                            ->count();
                                    })
                                    ->size('text-2xl')
                                    ->weight('bold')
                                    ->color('warning')
                                    ->icon('heroicon-o-calendar')
                                    ->formatStateUsing(function ($state) {
                                        $url = route('filament.app.resources.booking-departments.citas', ['tenant' => filament()->getTenant(), 'record' => $this->record]);
                                        return new \Illuminate\Support\HtmlString(
                                            "<a href='{$url}' class='text-warning hover:text-warning/80 underline decoration-offset-4' onclick='window.location.href=\"{$url}\"; return false;'>" . number_format($state) . " citas</a>"
                                        );
                                    }),

                                // Citas Hoy
                                TextEntry::make('citas_hoy')
                                    ->label('Citas Hoy')
                                    ->state(function () {
                                        return TaxistaAppointment::where('booking_department_id', $this->record->id)
                                            ->whereDate('starts_at', today())
                                            ->count();
                                    })
                                    ->size('text-2xl')
                                    ->weight('bold')
                                    ->color('primary')
                                    ->icon('heroicon-o-calendar-days')
                                    ->formatStateUsing(function ($state) {
                                        $url = route('filament.app.resources.booking-departments.citas', ['tenant' => filament()->getTenant(), 'record' => $this->record]);
                                        return new \Illuminate\Support\HtmlString(
                                            "<a href='{$url}' class='text-primary hover:text-primary/80 underline decoration-offset-4' onclick='window.location.href=\"{$url}\"; return false;'>" . number_format($state) . " citas</a>"
                                        );
                                    }),

                                // Tickets Abiertos
                                TextEntry::make('tickets_abiertos')
                                    ->label('Tickets Abiertos')
                                    ->state(function () {
                                        return TaxistaTicket::where('booking_department_id', $this->record->id)
                                            ->where('status', 'open')
                                            ->count();
                                    })
                                    ->size('text-2xl')
                                    ->weight('bold')
                                    ->color('danger')
                                    ->icon('heroicon-o-ticket')
                                    ->formatStateUsing(function ($state) {
                                        $url = route('filament.app.resources.booking-departments.tickets', ['tenant' => filament()->getTenant(), 'record' => $this->record]);
                                        return new \Illuminate\Support\HtmlString(
                                            "<a href='{$url}' class='text-danger hover:text-danger/80 underline decoration-offset-4' onclick='window.location.href=\"{$url}\"; return false;'>" . number_format($state) . " tickets</a>"
                                        );
                                    }),

                                // Total Documentos
                                TextEntry::make('total_documentos')
                                    ->label('Total Documentos')
                                    ->state(function () {
                                        return TaxistaDocument::whereHas('taxista', function ($query) {
                                            $query->where('booking_department_id', $this->record->id);
                                        })->count();
                                    })
                                    ->size('text-2xl')
                                    ->weight('bold')
                                    ->color('success')
                                    ->icon('heroicon-o-document')
                                    ->formatStateUsing(function ($state) {
                                        $url = route('filament.app.resources.booking-departments.documentos', ['tenant' => filament()->getTenant(), 'record' => $this->record]);
                                        return new \Illuminate\Support\HtmlString(
                                            "<a href='{$url}' class='text-success hover:text-success/80 underline decoration-offset-4' onclick='window.location.href=\"{$url}\"; return false;'>" . number_format($state) . " docs</a>"
                                        );
                                    }),

                                // Total Taxistas
                                TextEntry::make('total_taxistas')
                                    ->label('Total Taxistas')
                                    ->state(function () {
                                        return Taxista::where('booking_department_id', $this->record->id)->count();
                                    })
                                    ->size('text-2xl')
                                    ->weight('bold')
                                    ->color('info')
                                    ->icon('heroicon-o-users')
                                    ->formatStateUsing(function ($state) {
                                        $url = route('filament.app.resources.booking-departments.taxistas', ['tenant' => filament()->getTenant(), 'record' => $this->record]);
                                        return new \Illuminate\Support\HtmlString(
                                            "<a href='{$url}' class='text-info hover:text-info/80 underline decoration-offset-4' onclick='window.location.href=\"{$url}\"; return false;'>" . number_format($state) . " taxistas</a>"
                                        );
                                    }),
                            ]),
                    ]),
            ]);
    }
}
